import {test,expect} from "@playwright/test"
test("To place order for shoes",async({page})=>{
    await page.goto("https://demoapps.qspiders.com/")
    //await expect(page).toHaveURL("https://demoapps.qspiders.com/")
    await page.locator("//p[text()='UI Testing Concepts']").click()
    await page.locator("//section[text()='Dropdown']").click()
   // await page.locator("//input[@id='phone']").fill("9075141014")
   await page.fill("//input[@id='phone']","9075141016")
   await page.locator("//select[@id='select2']").selectOption('male')
    await page.locator("//select[@id='select3']").selectOption('India')
    await page.locator("//select[@id='select5']").selectOption('Karnataka')
    await page.locator("//label[text()='City']/../select").selectOption('Bijapur')
    //await page.locator("//select[@id='select7']").selectOption('2')
    await page.selectOption("//select[@id='select7']",'2')
    await page.locator("//button[@id='continuebtn']").click()
    await page.locator("(//input[@name='Attended'])[3]").check()
    await page.locator("(//input[@name='Willing'])[2]").check()
    await page.locator("//button[@id='btn']").click()
    await page.locator("(//input[@name='Domain'])[3]").check()
    await page.locator("(//input[@name='mode'])[4]").check()
    await page.locator("(//input[@name='mode'])[5]").check()
    await page.locator("//input[@type='submit']").click()
    await page.locator("(//label[@class='inline-flex items-center cursor-pointer'])[1]").click()
    await page.locator("(//label[@class='inline-flex items-center cursor-pointer'])[2]").click()
    await page.locator("//button[@id='togglers']").click()
    await expect(page.locator("//p[text()='Your Order has been successfully placed!']")).toHaveText('Your Order has been successfully placed!')
    //await page.pause()
})